name="COSMO-X"
version="version.txt"
author="Marcel Stahn"
maintainer="stahn@thch.uni-bonn.de"

[build]
link = ["lapack", "blas"]

[library]
source-dir="src"



[[executable]]
name="csx"
source-dir="app"
main="main.f90"

[dependencies]
numsa.git = "https://github.com/MtoLStoN/numsa"
mctc-lib.git = "https://github.com/grimme-lab/mctc-lib"
toml-f.git = "https://github.com/toml-f/toml-f.git"
